export const AUTH_PROGRESS = 'AUTH_PROGRESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const TASKS_LOADING = 'TASKS_LOADING';
export const TASK_LOAD_SUCCESS = 'TASK_LOAD_SUCCESS';
export const TASK_MARKED_AS_COMPLETED = 'TASK_MARKED_AS_COMPLETED';
export const TASK_SUBMITTED = 'TASK_SUBMITTED';
